### ISSUE TITLE
The link is broken

### ISSUE THREAD

**Issue by atapas** [hasura/learn-graphql#1055]
The deployed App link mentioned on this page is broken

![image](https://github.com/user-attachments/assets/f9a0b6f3-b87a-4ca2-8250-035a09d807bd)

Broken Link => https://learn-hasura-todo-app.netlify.com/

The tutorial I am referring to: https://github.com/hasura/learn-graphql/blob/master/tutorials/frontend/react-apollo-hooks/tutorial-site/content/introduction.md

**Comment by robertjdominguez** [comment]
HI @atapas — I'm taking a look at this and will get back here shortly!

**Comment by robertjdominguez** [comment]
@atapas — we no longer maintain that deployed instance, but I've updated the instructions to point to the locally-runnable instance that you can check out before diving into the course.

Additionally, do check out [hasura.io/ddn](https://hasura.io/ddn) and see the latest and greatest with Hasura 🙌
