### ISSUE TITLE
NextJs Demo not working

### ISSUE THREAD

**Issue by Omar-Bishtawi** [hasura/learn-graphql#1057]
## Description 
in this [tutorial page](https://github.com/hasura/learn-graphql/blob/master/tutorials/frontend/nextjs/tutorial-site/content/introduction.md) , there is a mention to this url https://learn-hasura-todo-app.netlify.com/ which is not working now and give 404 status page. 

## Expected actions 
replace this url with a correct working example.

**Comment by robertjdominguez** [comment]
Hi, @Omar-Bishtawi — this example is out-of-date, hence the non-functioning URL. We appreciate you bringing it to our attention, and we'll remove the reference 🙏
