### ISSUE TITLE
[Doc] typescript-react-apollo/codegen "document" config

### ISSUE THREAD

**Issue by li-yifei** [hasura/learn-graphql#127]
the "document" section from codegen.js seems not to work

```
"documents": [
    "./src/**/*.tsx",
    "./src/**/*.ts"
  ]
```
It throws such errors when I run `yarn graphql-codegen --config codegen.js`

```
✔ Parse configuration
  ❯ Generate outputs
    ❯ Generate ./src/generated/graphql.tsx
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unable to find any GraphQL type definitions for the following pointers: ./src/**/*.tsx, ./src/**/*.ts
        Generate
    ❯ Generate ./graphql.schema.json
      ✔ Load GraphQL schemas
      ✖ Load GraphQL documents
        → Unable to find any GraphQL type definitions for the following pointers: ./src/**/*.tsx, ./src/**/*.ts
        Generate


 Found 2 errors

```

**Comment by praveenweb** [comment]
Hi @li-yifei - This seems to occur when there are no GraphQL queries written inside the given path. Probably this step in the tutorial should be moved after writing the first query in the code, so that it works out of the box. 

Will make a PR to reflect the change.

**Comment by LeeByeongdo** [comment]
+1

**Comment by jamesrbedwell** [comment]
![image](https://user-images.githubusercontent.com/9282146/78424548-1403a800-76ba-11ea-9237-3371443c9379.png)
 Was just writing this then had the thought to check here.
