### ISSUE TITLE
Error in $: Failed reading: not a valid json value. Non informative error message

### ISSUE THREAD

**Issue by wzup** [hasura/learn-graphql#158]
I'm getting this not-informative error message. How can I see with Hasura what exactly was wrong with my json? Are there any options in Ui?
> Error in $: Failed reading: not a valid json value

```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "invalid-json"
      },
      "message": "Error in $: Failed reading: not a valid json value"
    }
  ]
}
```

My test request looks like this:
```
    return fetch(apiUrl, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json'
      },
      body: {
        query: "{ employee { id, name } }"
      }
    })
```

**Comment by praveenweb** [comment]
@wzup - Hi, you should be doing a JSON.stringify on the request body before sending the request to the server :) Since the server doesn't receive a valid JSON, it won't be able to parse the string to say where something has gone wrong.

**Comment by christophediprima** [comment]
I have the same issue but only for subscriptions

**Comment by praveenweb** [comment]
Closing this, as the error is about not passing in a valid JSON body.

**Comment by ahsanali60** [comment]
Here is the error I am getting while sending username and password as a parameter
I am also sending this data in JSON.stringify form


```
{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "unexpected"
      },
      "message": "Error in $: not enough input"
    }
  ]
}
```

**Comment by L-U-C-K-Y** [comment]
We are also this error occurring often, after using Hasura as our main gateway and using the old schema as a subschema.

We notice this happens often when there is a high load, are there any other experiences?

**Comment by CuriousLearner** [comment]
Hi @L-U-C-K-Y 

Did you figure out this issue?
