### ISSUE TITLE
Improper use of optimisticResponse

### ISSUE THREAD

**Issue by calendee** [hasura/learn-graphql#165]
I noticed while following the React/Apollo tutorials (https://hasura.io/learn/graphql/react/optimistic-update-mutations/), that the view is not updating optimistically. Instead, it is waiting for the mutation to complete on the backend before updating the UI.

The reason appears to be examples like this in the tutorial:

```
clearCompleted() {
+  clearCompletedTodos({
+    optimisticResponse: null, // Here is the issue
+    update: (cache, {data}) => {
+      const existingTodos = cache.readQuery({ query: GET_MY_TODOS });
+      const newTodos = existingTodos.todos.filter(t => (!t.is_completed));
+      cache.writeQuery({query:GET_MY_TODOS, data: {todos: newTodos}});
+    }
+  });
}
```

I will start a PR to change these to:

```
optimisticResponse: true
```

**Comment by dannyshisler** [comment]
This looks good, I'm new to Apollo and Hasura and this really confused me. The associated PR should definitely be merged ASAP.
