### ISSUE TITLE
Cannot login on boilerproject react native

### ISSUE THREAD

**Issue by chazzaoui** [hasura/learn-graphql#167]
Hi people,

I am following the 2 hour tutorial to graphQl with Hasura. Currently experiencing an issue with login in and signup in the expo boilerplate. The server responds with an error 
<img width="1118" alt="Schermafbeelding 2020-03-08 om 22 09 34" src="https://user-images.githubusercontent.com/22476835/76171268-89e32500-6189-11ea-807a-13d408538897.png">

Also tried to send some data to the url via Postman and responds with the same error 
<img width="593" alt="Schermafbeelding 2020-03-08 om 22 11 13" src="https://user-images.githubusercontent.com/22476835/76171295-c020a480-6189-11ea-94ae-a6e6b5e0336b.png">

Does someone know what the issue might be? the code is unchanged and i am pretty sure it is a server issue.

**Comment by briantofu** [comment]
Kindly change the links for 'authActions.js'

for expo const signup fetch
"https://hasura.io/learn/auth/signup"

for expo const login fetch
"https://hasura.io/learn/auth/login"

This should work like a charm! 💯

**Comment by chazzaoui** [comment]
Works like a charm! 🔥
