### ISSUE TITLE
Edit on Insert Row becomes uniqueness violation.

### ISSUE THREAD

**Issue by yoshwata** [hasura/learn-graphql#170]
https://hasura.io/learn/graphql/hasura/data-transformations/

This page might have a wrong explanation. When I tried to update `users` from `Insert Row` tab, I met with the uniqueness violation error. It should be done from `Edit row` button of users table menu.

![Screen Shot 2020-03-15 at 14 16 10](https://user-images.githubusercontent.com/32473622/76695965-cbfbf180-66c8-11ea-9a97-7269687a76e7.jpg)

**Comment by praveenweb** [comment]
@yoshwata - Thanks for pointing out. Fixed the screenshot. Previously the console UI edits went to Insert tab. A recent update takes you to the edit tab separately.
