### ISSUE TITLE
How to add x-hasura-admin-secret to WebSocketLink in React JS

### ISSUE THREAD

**Issue by JohnMusleh** [hasura/learn-graphql#172]
resolved with
```js
const wsLink = new WebSocketLink({
  uri: `${wsEndpoint}`,
  options: {
    reconnect: true,
 connectionParams: {
      headers: {
        'x-hasura-access-key': `${secret}`
      }
    }
  },
});
```

**Comment by k96white** [comment]
Hi JohnMusleh , i am trying this with ApolloClient , will it work as I am getting this error while fetching the data

**[GraphQL error]: Message: x-hasura-admin-secret/x-hasura-access-key required, but not found, Location: undefined, Path: undefined**

**Comment by smartcris** [comment]
> resolved with
> 
> ```js
> const wsLink = new WebSocketLink({
>   uri: `${wsEndpoint}`,
>   options: {
>     reconnect: true,
>  connectionParams: {
>       headers: {
>         'x-hasura-access-key': `${secret}`
>       }
>     }
>   },
> });
> ```

Aren't you exposing sensitive information on the client side?

**Comment by ChrisBurgdorff** [comment]
> Aren't you exposing sensitive information on the client side?

Not OP, but I often have a regular Apollo client and one that uses the admin key for my Next.JS apps. You can use the admin one in the backend in case you ever need to make an unauthenticated query (happens sometimes).
