### ISSUE TITLE
unexpected variables: polygon

### ISSUE THREAD

**Issue by areski** [hasura/learn-graphql#173]
I'm getting a strange error message `unexpected variables: polygon` when using https://hasura.io/learn/graphql/graphiql:

![image](https://user-images.githubusercontent.com/53455/78273011-8d5e9780-750e-11ea-949a-81e76f45f1f7.png)

**Comment by praveenweb** [comment]
@areski - Can you check the variables section in GraphiQL? Right at the bottom of where you write the query. It seems like some variable called polygon is defined. Removing it should make it work.

**Comment by areski** [comment]
I didn't even noticed I had some variables there, sorry for the fake alarms.
Thanks for your hard work!
