### ISSUE TITLE
update react tutorial to support apollo client v3

### ISSUE THREAD

**Issue by praveenweb** [hasura/learn-graphql#190]
The current react tutorial uses Apollo Client v2 stable. v3 changes some of the APIs. We can update the tutorial with the necessary changes.

- cache.read and cache.write are replaced with cache.modify.

// TODO: Add more changes here.

**Comment by kriswep** [comment]
I could do this.
Currently, there are two react tutorials here, `react-apollo` and `react-apollo-hooks`. 
The version on https://hasura.io/learn/ seems to be the `react-apollo-hooks, correct?

**Comment by praveenweb** [comment]
@kriswep - Yes! `react-apollo-hooks` is the latest one and maintained. The `react-apollo` is the old one that uses Apollo Components and we don't maintain that anymore and is there just for reference code.

Apollo has released [v3.0.0-rc.0](https://github.com/apollographql/apollo-client/blob/v3.0.0-rc.0/CHANGELOG.md). Might be good to break down what changes for the current tutorial. 

High level, I see that 
- Packages have changed (@apollo/client replaces apollo-boost and a few others). 
- Managing cache needs to be updated.
- Optimistic UI usage might need an update.
- Verify if there are changes to subscriptions.

**Comment by kriswep** [comment]
Yes, nice. 
I‘d follow apollos‘ [migration guide](https://www.apollographql.com/docs/react/v3.0-beta/migrating/apollo-client-3-migration/) and figure things out from there.
