### ISSUE TITLE
Explicit cache update not needed when valid optimisticResponse defined in react apollo hooks?

### ISSUE THREAD

**Issue by martinpengellyphillips** [hasura/learn-graphql#193]
Shouldn't the `react-apollo-hooks/tutorial-site/content/optimistic-update-mutations/2-mutation-cache.md` example just define a valid `optimisticResponse` and skip defining the cache `update` as that will be [handled automatically by Apollo](https://www.apollographql.com/docs/react/performance/optimistic-ui/#basic-optimistic-ui) for a simple update?

E.g. 

```js
  const toggleTodo = () => {
    toggleTodoMutation({
      variables: { id: todo.id, isCompleted: !todo.is_completed },
      optimisticResponse: {
        update_todos: {
          __typename: 'todos_mutation_response',
          affected_rows: 1,
          returning: [
            {
              __typename: 'todos',
              id: todo.id,
              is_completed: !todo.is_completed
            }
          ]
        }
      },
    })
  }
```

Note that I am new to Hasura, Apollo and GraphQL so might be wrong about this 😄

**Comment by praveenweb** [comment]
@martinpengellyphillips - Hi, you are right. Defining an optimistic response should do just fine. The tutorial goes over different ways of doing things to cover all sorts of use cases in this small todo app 😄  (Like optimistic UI, manual cache updates, using client.query vs useQuery hook) and hence the usage.
