### ISSUE TITLE
[Flutter Tutorial - Need Help] Error when signing up or logging in into the boilerplate todo app

### ISSUE THREAD

**Issue by ammarfaris** [hasura/learn-graphql#196]
I'm trying to follow the tutorial https://hasura.io/learn/graphql/flutter-graphql/setup/.

The app from https://hasura.io/learn/graphql/flutter-graphql/boilerplate.zip built successfully but when I try to sign up or login, the spinner kept on spinning on my emulators and I get the errors below in the Android Studio -  Run console:

I really think Hasura has a lot of potential. Thank you in advance for your assistance! 

**`E/flutter ( 8548): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FormatException: Unexpected end of input (at character 1)`**

`E/flutter ( 8548): `

`E/flutter ( 8548): ^`

`E/flutter ( 8548): `

`E/flutter ( 8548): #0      _ChunkedJsonParser.fail (dart:convert-patch/convert_patch.dart:1394:5)`

`E/flutter ( 8548): #1      _ChunkedJsonParser.close (dart:convert-patch/convert_patch.dart:512:7)`

`E/flutter ( 8548): #2      _parseJson (dart:convert-patch/convert_patch.dart:32:10)`

`E/flutter ( 8548): #3      JsonDecoder.convert (dart:convert/json.dart:505:36)`

`E/flutter ( 8548): #4      JsonCodec.decode (dart:convert/json.dart:153:41)`

`E/flutter ( 8548): #5      jsonDecode (dart:convert/json.dart:96:10)`

`E/flutter ( 8548): #6      HasuraAuth.signup (package:app_boilerplate/services/auth.dart:45:15)`

`E/flutter ( 8548): <asynchronous suspension>`

`E/flutter ( 8548): #7      _SignupState.build.<anonymous closure> (package:app_boilerplate/screens/signup.dart:73:48)`

`E/flutter ( 8548): #8      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182:24)`

`E/flutter ( 8548): #9      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:504:11)`

`E/flutter ( 8548): #10     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:282:5)`

`E/flutter ( 8548): #11     BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:217:7)`

`E/flutter ( 8548): #12     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:475:9)`

`E/flutter ( 8548): #13     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:76:12)`

`E/flutter ( 8548): #14     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)`

`E/flutter ( 8548): #15     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:379:8)`

`E/flutter ( 8548): #16     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)`

`E/flutter ( 8548): #17     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)`

`E/flutter ( 8548): #18     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:218:19)`

`E/flutter ( 8548): #19     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:198:22)`

`E/flutter ( 8548): #20     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:156:7)`

`E/flutter ( 8548): #21     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:102:7)`

`E/flutter ( 8548): #22     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:86:7)`

`E/flutter ( 8548): #23     _rootRunUnary (dart:async/zone.dart:1196:13)`

`E/flutter ( 8548): #24     _CustomZone.runUnary (dart:async/zone.dart:1085:19)`

`E/flutter ( 8548): #25     _CustomZone.runUnaryGuarded (dart:async/zone.dart:987:7)`

`E/flutter ( 8548): #26     _invoke1 (dart:ui/hooks.dart:275:10)`

`E/flutter ( 8548): #27     _dispatchPointerDataPacket (dart:ui/hooks.dart:184:5)`

Thanks @praveenweb and others...

**Comment by clebermacieski** [comment]
Hi @ammarfaris. Try to clone and build the version from here, versioned at GitHub. The url to the backend changed, but de .zip for tutorial that you have maybe is not updated.
**But**, the package graphql_flutter, is outdated (1.0). I had a exception with that too. To solve I fork this repo and used the version ^3.0.0 (actually 3.0.1). The interfece changed a little bit. Check my fork to note the diffs.
**But**, seems like the subscriptons isn't working. Probably is a problem with de graphql_flutter. If you discover something about that, please tell me.

**Comment by clebermacieski** [comment]
To me, the subscriptions isn't working because of this error:
{extensions: {path: $, code: start-failed}, message: cannot start as connection_init failed with : Authentication hook unauthorized this request}
So, nothing related to graphql_flutter 3.0.1.

**Comment by RogueBumbler** [comment]
Hey @ammarfaris - same problem here.

Stuck just beyond the sign up page with the same list of errors.

@clebermacieski do you have that link to the version on Github - or do you have the new backend URL?

Thanks guys

**Comment by clebermacieski** [comment]
> Hey @ammarfaris - same problem here.
> 
> Stuck just beyond the sign up page with the same list of errors.
> 
> @clebermacieski do you have that link to the version on Github - or do you have the new backend URL?
> 
> Thanks guys

Hi @RogueBumbler , checkout the version here at this repo, and the URL will be updated. The URL problem seems to be only in the .zip from the tutorial site.

And after You can checkout my fork ( https://github.com/clebermacieski/learn-graphql ) where I made some changes in the tutorial to work with the latest version of graphql_flutter, what solve the problems of this issue. But still I am stuck with the error in subscription that I describe in other issue here.

**Comment by praveenweb** [comment]
@ammarfaris @RogueBumbler - The boilerplate zip has been updated to have the right URL. Closing this.
