### ISSUE TITLE
[Flutter] Subscriptions not working

### ISSUE THREAD

**Issue by clebermacieski** [hasura/learn-graphql#210]
The queries are OK, but seems like subscriptions have a problem with the authorization with the socket.
In my fork oh this repo have a version of the boilerplate updated to work with the latest version of the graphql_flutter, but can't figure out how to make the subscriptions work.
Someone know what is the problem?

{extensions: {path: $, code: start-failed}, message: cannot start as connection_init failed with : Authentication hook unauthorized this request}

![hasura_flutter_tutorial_error](https://user-images.githubusercontent.com/26489056/82130026-0d2e8180-979e-11ea-94c1-721e0ce5a504.gif)

**Comment by divjakLab** [comment]
@clebermacieski I just added PR. Problem is that in Subscription you don't send Token with it.
