### ISSUE TITLE
Unable to signup in boilerplate setup

### ISSUE THREAD

**Issue by sagarnatekar** [hasura/learn-graphql#225]
Hi,

I'm following the instructions here: https://hasura.io/learn/graphql/react-native/setup/, but can't get signup to work. I'm getting unexpected error every time. 

Is this signup url correct: https://hasura.io/learn/auth/signup ?.

Thanks.

**Comment by praveenweb** [comment]
@sagarnatekar - Can you post debug logs for us to look into?

**Comment by aseef17** [comment]
> @sagarnatekar - Can you post debug logs for us to look into?

The login and Signup URLs seem to be down. I tried it in Postman but it doesn't seem to work

**Comment by sagarnatekar** [comment]
@praveenweb This ^

Only thing I see in the logs is:
```
JSON Parse error: Unrecognized token '<'
- node_modules/promise/setimmediate/core.js:37:14 in tryCallOne
- node_modules/promise/setimmediate/core.js:123:25 in <unknown>
- ... 8 more stack frames from framework internals
```

**Comment by arthuryeti** [comment]
https://hasura.io/learn/auth/signup is not the signup url. It should look like this => http://localhost:8080/signup

**Comment by praveenweb** [comment]
@arthuryeti - The signup URL is `https://hasura.io/learn/auth/signup` and the login URL is `https://hasura.io/learn/auth/login`

@sagarnatekar @aseef17 - The auth server has been fixed now. The signup and login should work as expected.
