### ISSUE TITLE
Angular Tutorial breaks on "Run mutation, update cache" page

### ISSUE THREAD

**Issue by dylanesque** [hasura/learn-graphql#228]
Everything works just fine up until [this page](https://hasura.io/learn/graphql/angular-apollo/mutations-variables/3-create-mutation/), specifically complaining that:

`Property 'insert_todos' does not exist on type '{}'`

and: 

` Property 'loading' does not exist on type 'ExecutionResult<{}> & { extensions?: Record<string, any>; context?: Record<string, any>; }'.`

**Comment by mpimiller** [comment]
I'm seeing the same issue.  Any idea when this will be resolved?

**Comment by outofgamut** [comment]
@praveenweb - i can take a look at this one if you want to assign me it.

**Comment by praveenweb** [comment]
Hey @outofgamut! Sure, I have assigned it to you. Do let me know if you need any help.

**Comment by outofgamut** [comment]
How much work can/should I put into this one? A lot can be updated in this example. I'd be open to rewriting it and updating it to Angular 10.

**Comment by hirenchauhan2** [comment]
Hi All,
You can review my pull #348 for this, this will resolve this issue!
Also, I have migrated the angular final project to Angular 9. I tried Angular 10 but, I had some issues.
