### ISSUE TITLE
ERR_CONNECTION_REFUSED when refreshing page

### ISSUE THREAD

**Issue by TechStacker** [hasura/learn-graphql#232]
Hi, 

If you refresh your browser after logging in on the production demo https://learn-hasura-todo-app.netlify.app/
 I get this error: 

````
This site can’t be reachedlocalhost refused to connect.
Try:

Checking the connection
Checking the proxy and the firewall
ERR_CONNECTION_REFUSED

````

It looks like the server tries to run the app on localhost:3000 while in production.

**Comment by praveenweb** [comment]
Hi @TechStacker - We have fixed this now.
