### ISSUE TITLE
Tweaks to index page

### ISSUE THREAD

**Issue by sezgi** [hasura/learn-graphql#233]
- [ ] Body font size should be at least 18px (for higher resolutions) (see https://dokz.site/)

- [ ] Change "The Real world GraphQL tutorials" to "Real world GraphQL tutorials"

- [ ] Change "our hands-on tutorial" to "our hands-on tutorials"

**Comment by praveenweb** [comment]
@sezgi - Moving this issue to the learn homepage repo.
