### ISSUE TITLE
[WIP] UI tweaks to learn pages

### ISSUE THREAD

**Issue by sezgi** [hasura/learn-graphql#234]
- [ ] Change body font size to at least 16px (for higher resolutions)

- [ ] Change font to Open Sans

**Comment by Ninjavin** [comment]
Hey, @sezgi Can I take this issue?

**Comment by DevLokCodes** [comment]
I would like to work on this issue

**Comment by sezgi** [comment]
This issue is most likely outdated. @praveenweb please update/close if so.

**Comment by praveenweb** [comment]
Closing, since this is outdated.
