### ISSUE TITLE
Flutter Tutorial is broken or outdated

### ISSUE THREAD

**Issue by jgluck93** [hasura/learn-graphql#288]
I was trying to follow the flutter walkthrough located here.
 https://hasura.io/learn/graphql/flutter-graphql/introduction/

and noticed it is missing information or is outdated. The issue starts on this page https://hasura.io/learn/graphql/flutter-graphql/graphql-client/

`static final AuthLink authLink = AuthLink(getToken: () => _token);` is the line that seems to start the issue. `_token` is never declared. Also the `static ValueNotifier<GraphQLClient> initailizeClient(String token)` function takes a token string as a parameter but when we use this function in the tutorial we never pass it a token nor is it explained how to get the token. You can see that here 
```return DefaultTabController(
  return GraphQLProvider(
    client: Config.initailizeClient(),
    child: CacheProvider(
     child: DefaultTabController(
          . . .
       ),
     ),
    );```

**Comment by Himanshu-Nagle** [comment]
I want to work on this issue. Please assign me

**Comment by Himanshu-Nagle** [comment]
@jgluck93 let me if problem still exist.
