### ISSUE TITLE
angular-apollo project - final app won't compile

### ISSUE THREAD

**Issue by mpimiller** [hasura/learn-graphql#293]
This project starts to compile and progresses to close to 80% before throwing this error: 

src/app/OnlineUsers/OnlineUsersWrapper.ts:60:31 - error TS2339: Property 'loading' does not exist on type 'ExecutionResult<{}> & { extensions?: Record<string, any>; context?: Record<string, any>; }'.

the boilerplate version does the same thing when you get part way through the lesson.

**Comment by mpimiller** [comment]
Can somebody please take a look at this?

**Comment by hirenchauhan2** [comment]
Hi,
I would like to work on this issue, I have some idea about it.
Can you please assign it to me?
