### ISSUE TITLE
Auth0, NextJS tutorial state mismatch, expected

### ISSUE THREAD

**Issue by raykanani** [hasura/learn-graphql#295]
I'm on NextJS boilerplate setup. After adding the .env details, when I try to log-in I get

`state mismatch, expected eyJub25jZSI6IjdkODc2NWU4ODM4NzRmM2FmYTVmNTRlMzc5OTNiZDVlIn0, got: g6Fo2SAtUWgwbTZlZGNidlJaTTIzaDFTTzFrb3lGTTZRSWVYRqN0aWTZIFJNbGloU3p2TnVFeUZhdVhrb1NsVXJaLUlncjVVOFRro2NpZNkgRmNDV0ZDVmFuMG00MnNIVUNJY0Y4cENBekN1MDB0Qm4`

Any help is appreciated. Thanks

**Comment by praveenweb** [comment]
@raykanani - Hey this happens when the audience value is not configured correctly. Can you recheck?

**Comment by raykanani** [comment]
Yep, I figured it out.

As a note, I think the tutorial might be inaccurate on the Auth0 audience being 'hasura'

I had to change the audience value to 'https://hasura.io/learn' as per the tutorial for it to work.

**Comment by praveenweb** [comment]
Closed via a775eca701a91a06dfd2a97cf3b30aeb9784635d
