### ISSUE TITLE
Can I use  react-query as GraphQL client?

### ISSUE THREAD

**Issue by zwl1619** [hasura/learn-graphql#296]
I saw the article  [Fetch your GraphQL data automagically: Building a movie app with Hasura & gqless](https://medium.com/hasura/fetch-your-graphql-data-automagically-building-a-movie-app-with-hasura-gqless-f7ad2549c8fd) on medium , it uses  gqless as GraphQL client, but it doesn't have mutations and local state management now.

Can I use  [react-query](https://github.com/tannerlinsley/react-query) as GraphQL client?

And is it possible to write an article on "Building a blog app with Hasura & next.js & react-query & Serverless"?

**Comment by GavinRay97** [comment]
Yes, here is a full example written for you, using React Query and Pokemon test API :slightly_smiling_face: 

https://codesandbox.io/s/stoic-moser-751wt?file=/src/index.js

**Comment by yogeshwar607** [comment]
@GavinRay97  you might need to make some changes in https://codesandbox.io/s/stoic-moser-751wt?file=/src/index.js as per react-query v3 or keep react-query to v2 to keep above example working
