### ISSUE TITLE
learn: add lightbox for images in tutorials

### ISSUE THREAD

**Issue by ajeetdsouza** [hasura/learn-graphql#3]
Some of the images are too tiny to see clearly. Perhaps a lightbox would help?

**Comment by ShivamRawat0l** [comment]
Working on it

**Comment by adityakaria** [comment]
I'd love to work on this, please! Kindly assign to me if not assigned already.

**Comment by deadcoder0904** [comment]
@ShivamRawat0l still working? if not, i'd like to take it up :)

**Comment by praveenweb** [comment]
Moving the scope of this issue to [hasura/gatsby-gitbook-starter](https://github.com/hasura/gatsby-gitbook-starter) which powers the learn tutorial UI. 

Closing this issue now.
