### ISSUE TITLE
fix auth0 references

### ISSUE THREAD

**Issue by dakkafex** [hasura/learn-graphql#310]
It seems to be full of either outdated references, or just incomplete explanation, mainly in the Auth0 part

**Comment by praveenweb** [comment]
@dakkafex - Hi, can you let us know which specific tutorial you are trying out so that we can make a fix?

Also, we are updating Auth0 specific integrations to match their latest updates (`idToken` to `accessToken` usage and so on), although the current tutorial should continue to work.

**Comment by praveenweb** [comment]
Auth0 reference material has been updated via https://github.com/hasura/learn-graphql/pull/319. Closing this now.
