### ISSUE TITLE
Unauthenticated access to public todos

### ISSUE THREAD

**Issue by raykanani** [hasura/learn-graphql#311]
I've been trying to figure out how to get view access to public todos for an unauthenticated user. Any help is appreciated.

*Things I've tried* 
Creat the public role in the schema permissions and given it view access when is_public is true.

Expose the public todo UI when user isn't logged in. Returns the error

`Error {"extensions":{"path":"$","code":"start-failed"},"message":"cannot start as connection_init failed with : Could not verify JWT: JWSError (CompactDecodeError Invalid number of parts: Expected 3 parts; got 1)"}' on the UI

and error on server
`AccessTokenError: The user does not have a valid session.`

I've experimented with adding the env variable `HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public`

No luck

**Comment by praveenweb** [comment]
Have you tried the unauthenticated query from the Hasura Console GraphiQL? You don't need to pass in headers for this and it should ideally work.

In your case, what I believe is happening is that Apollo Client sends an Authorization header for all requests and the token value is null. If you want to make an unauthenticated request, try sending the query without the Authorization header which will turn it into an unauthenticated request and Hasura will apply the public role permissions as configured in the env.

**Comment by raykanani** [comment]
Thanks @praveenweb 

Do you know what I need to modify in the apolloClient.js to send unauthenticated requests without the header?

I'm assuming because we wrapped withApollo in index.js all requests are sent via apollo client?

**Comment by raykanani** [comment]
As a note, when testing with GraphiQL console and sending no headers, I get this response

`{
  "errors": [
    {
      "extensions": {
        "path": "$",
        "code": "invalid-headers"
      },
      "message": "Missing Authorization header in JWT authentication mode"
    }
  ]
}`

**Comment by raykanani** [comment]
Figured out that the .env variable `HASURA_GRAPHQL_UNAUTHORIZED_ROLE=public` has to be added to the environment variable on DB (heroku). Got GaphiQL working :) but still struggling with modifying apolloClient to not send headers if user is not logged in.

**Comment by praveenweb** [comment]
@raykanani - I'm closing this issue now since you have figured out the env to be added.

And sorry about missing this earlier :) Hope you found a way to solve ApolloClient to send different headers based on user login status.

**Comment by DomVinyard** [comment]
>  still struggling with modifying apolloClient to not send headers if user is not logged in.

did you find a solution to this?

**Comment by raykanani** [comment]
Yes I did. Create a new role in the access table. It can be called whatever you like "public" or "anonymous" are popular choices. Set the access rights of that user.

Set the env variable in hasura for HASURA_GRAPHQL_UNAUTHORIZED_ROLE to the name of that role

example HASURA_GRAPHQL_UNAUTHORIZED_ROLE=Public

That way all unauthenticated users will be assigned that role and have the access you set for it.
