### ISSUE TITLE
Learn Course Enhacement

### ISSUE THREAD

**Issue by mehtavishwa30** [hasura/learn-graphql#314]
Update the Hasura Backend Learn course for the following enhancements:

- [ ] Enhance Language to make beginner friendly

- [ ] Fix typos & grammatical errors

- [ ] Remove usage of the terms easy, simple, just & the likes of it

- [ ] Enhance Examples for readability

- [ ] Improve Data Modelling section

- [ ] Improve Relationships section

- [ ] Improve Data Transformations section

- [ ] Improve Authorization section

- [ ] Improve Authentication section section

**Comment by galihmelon** [comment]
I'm interested to contribute on this. However, I'm not sure how to update the images and I can't found relevant information in the contributing guidelines for that.
How shall we update images?

**Comment by praveenweb** [comment]
Closed via #371
