### ISSUE TITLE
RxDB tutorial feedback

### ISSUE THREAD

**Issue by sw-yx** [hasura/learn-graphql#320]
hi folks!

i ran through the rxdb tutorial on stream today: https://youtu.be/bFyGNA2LA0w and found some issues that i figured i should share with you:

- it is not clear how to set up the auth0 callback URL correctly for running in localhost
- instructions to install `subscriptions-transport-ws` and `pouchdb-adapter-idb` are missing
- instructions to import `Database.js` and `uuid/v4` are missing
- instructions to pass `db` as props into the app are missing.
- it would be nice to warn that must use `rxdb@8.7.4` as later versions are broken

i did not manage to get thru the tutorial in 1 hr even with good graphql/react knowledge.

hope this helps you improve the tutorial!

**Comment by praveenweb** [comment]
@sw-yx - Hi Shawn, thanks for the feedback. We will push an update to the tutorial addressing these issues.

**Comment by rossng** [comment]
I experienced many of the same issues. At the moment, it's near-impossible to complete this tutorial without a lot of head-desking 😕
