### ISSUE TITLE
Todos table update permission

### ISSUE THREAD

**Issue by ndeitch** [hasura/learn-graphql#333]
Hi folks,

Why [here](https://github.com/hasura/learn-graphql/blob/master/tutorials/backend/hasura/tutorial-site/content/authorization/1-todos-table-permissions.md#update-permission)

> Now click on edit icon for "update" permissions. In the custom check, choose With same custom checks as insert.
>
> And under column update permissions, select the is_completed column.

The permission is only on `is_completed`? IMHO should be `is_completed` and `title` don't?

Thanks

**Comment by praveenweb** [comment]
Hi @ndeitch - You are right. We left it intentionally because the tutorial app doesn't allow editing the todo text that's already created. But in a typical real scenario, editing todos makes sense and the permission rule has to be updated accordingly.

**Comment by ndeitch** [comment]
Got it, closing it so.
