### ISSUE TITLE
update auth0 instructions in nextjs tutorial

### ISSUE THREAD

**Issue by praveenweb** [hasura/learn-graphql#334]

**Comment by Akshay-Nagle** [comment]
I want to work on this issue. I checked the Auth0 instruction but I didn't found any major problem in instruction except some grammatical and use of punctuation mistakes. Kindly please tell me what do you want to update.

**Comment by praveenweb** [comment]
@Akshay-Nagle - Hey we wanted to update instruction for Auth0 and Hasura connection to have `JWK_URL` usage. But figured out that some applications in Auth0 still had issues with that usage. I reverted the changes for backend tutorial in this [commit](https://github.com/hasura/learn-graphql/commit/dbca001efc4b1ed4b124d2979d70c8d7c857b1e3).

Closing this issue as it's not relevant anymore.
