### ISSUE TITLE
Multiple Typos in backend tutorials - access control section

### ISSUE THREAD

**Issue by anup-a** [hasura/learn-graphql#339]
>  acccess, 

Access is mispelled 1-user-permissions.md, 2-workspace-permissions.md, 3-channel-permissions.md, 4-threads-messages-permissions.md 

> permisisons

permissions mispelled in 1-user-permissions.md 

Could the team add hacktoberfest label here?
I already created PR fixing this.

**Comment by anup-a** [comment]
Checkout the PR - https://github.com/hasura/learn-graphql/pull/338

**Comment by praveenweb** [comment]
Hi @anup-a - Thanks for your PR. Merged now.
