### ISSUE TITLE
Schema download returns 404

### ISSUE THREAD

**Issue by rabyunghwa** [hasura/learn-graphql#349]
Hello!

I tried to download the schema by using my own access token. However, it returns **404**:

> apollo client:download-schema OUTPUT --endpoint=http://hasura.io/learn/graphql --header="Authorization: Bearer MY_OWN_ACCESS_TOKEN".

> Project": Error: ServerError: Response not successful: Received status code 404

Any help is greatly appreciated!

**Comment by praveenweb** [comment]
@rabyunghwa - Can you try the `https` version of the URL?

`https://hasura.io/learn/graphql` for the endpoint.

**Comment by rabyunghwa** [comment]
@praveen-x It worked! Thank you very much! It would be great if you could update [your tutorial](https://hasura.io/learn/graphql/android/apollo-client/) accordingly:

![Screenshot 2020-10-05 194704](https://user-images.githubusercontent.com/7411385/95070834-a9542780-0743-11eb-87b6-d638c2b78e1b.png)
