### ISSUE TITLE
Enhancing contribution guidelines

### ISSUE THREAD

**Issue by ng29** [hasura/learn-graphql#359]
hi @praveenweb 

would like to create a contributing.md file
similar to https://github.com/smaranjitghose/awesome-portfolio-websites/blob/master/CONTRIBUTING.md , if you are ok with the design I woud like to design contributing.md file for this project too please assign the issue to me.

Cheers,

**Comment by praveenweb** [comment]
@ng29 - Hey, feel free to make a PR. That template does look good for beginners to follow along.
