### ISSUE TITLE
Setting HASURA_GRAPHQL_JWT_SECRET error

### ISSUE THREAD

**Issue by ruliarmando** [hasura/learn-graphql#382]
So, im following the nextjs hasura tutorial, first problem occured when i tried to generate jwt config via https://hasura.io/jwt-config, but i won't generate any config for me, it keeps spitting error like "please input valid value" or something and then i tried generating the certificate manually but when tried to define the environment variables in hasura cloud it spits this error.

![error](https://user-images.githubusercontent.com/2479917/99188925-2b972900-2791-11eb-8693-e33544c740d8.png)

Is the tutorial somehow outdated?

**Comment by praveenweb** [comment]
@ruliarmando - Before configuring `HASURA_GRAPHQL_JWT_SECRET` env variable, you will need to set an admin secret. This was earlier added by default on a Hasura Cloud project and hence this course assumed an admin secret. To fix this, you will need to add `HASURA_GRAPHQL_ADMIN_SECRET` env to your project first and then proceed with the JWT steps.
