### ISSUE TITLE
course title first in page titles?

### ISSUE THREAD

**Issue by robx** [hasura/learn-graphql#385]
I'd like to suggest change the page titles to start with the course name. The primary reason being that I find reading a truncated  "Hasura GraphQL Tutorial..." a lot more helpful when I'm trying to navigate back to the course tab than e.g. "Course Introduction...".

<img width="317" alt="Screenshot 2020-11-16 at 20 12 52" src="https://user-images.githubusercontent.com/132113/99297418-88094f80-2848-11eb-8bd7-3942dc35b89e.png">

**Comment by praveenweb** [comment]
@robx - Hey Rob, Interesting use case. The original reason for having page-specific titles at the beginning is to make it friendly for organic search. If users see the results with a title tag being in the format `Course name | Page title` it would truncate the page-specific portion for search results making it slightly difficult to understand the goal of the particular page. 
I'm guessing hovering over the tab is an option in this use case whereas it's not so much in organic search and hence closing this issue in favor of that.
