### ISSUE TITLE
Add Keycloak Integration Tutorial in learn.hasura.io

### ISSUE THREAD

**Issue by mnlbox** [hasura/learn-graphql#4]
Hi guys,
I see that https://learn.hasura.io is a very helpful resource for creating application with Hasura and other useful stuff.
Now authentication tutorial is based on Auth0 I think another authentication tutorial also can be useful for example now we have https://www.keycloak.org/ as an open source alternative for https://auth0.com.
Keycloak also have a good production ready Hasura connector here:  (Thanks to @httpsOmkar)
https://github.com/httpsOmkar/keycloak-hasura-connector

I think such tutorial can be very useful here:
https://learn.hasura.io/graphql/hasura/authentication

Thanks for your attention

**Comment by mckraemer** [comment]
Any updates? I would also be interested in a tutorial with Keycloak.

**Comment by jtiagodev** [comment]
Any updates?

**Comment by edulix** [comment]
It'd be great if we could have a well documented open source system for authentication in Hasura and Keycloak seems to be the obvious choice.

**Comment by ctwhome** [comment]
More than updates? Any thoughs about it?

**Comment by bigabig** [comment]
Is this step also possible with Keycloak? 
https://hasura.io/learn/graphql/hasura/authentication/4-user-sync-rule/

**Comment by venom90** [comment]
Any updates on this?

**Comment by mgnanaprakash11** [comment]
@praveenweb Can we have a tutorial on this. It will be great.

**Comment by praveenweb** [comment]
Hey all,

We have added an [example Keycloak integration](https://hasura.io/learn/graphql/hasura-authentication/integrations/keycloak/) in the new Authentication tutorial. There's also examples for other popular providers as well. Thanks everyone for requesting these and being patient 🙏
