### ISSUE TITLE
wrong field name "created" in 3-writing-data-mutations.md of reason-react-apollo tutorial 

### ISSUE THREAD

**Issue by adityakrshnn** [hasura/learn-graphql#402]
Hi,

There is a small typo in [3-writing-mutations.md](https://github.com/hasura/learn-graphql/blob/master/tutorials/frontend/reason-react-apollo/tutorial-site/content/intro-to-graphql/3-writing-data-mutations.md#returning-data-after-the-mutation) of the reason-react-apollo tutorial. Instead of "created" it should've been "created_at" to be working without errors.

**Comment by praveenweb** [comment]
Closed via https://github.com/hasura/learn-graphql/commit/3045dbb0a28ca6afedbc0905af5ff6ea9687fb36
