### ISSUE TITLE
"npx send-introspection-query" no longer works to fetch schema

### ISSUE THREAD

**Issue by adityakrshnn** [hasura/learn-graphql#404]
npx send-introspection-query in [apollo client installation](https://github.com/hasura/learn-graphql/blob/master/tutorials/frontend/reason-react-apollo/tutorial-site/content/apollo-client.md#installation) section no longer works and gives 404. Instead, we should use Apollo CLI itself to fetch schema.

**Comment by praveenweb** [comment]
Closed via https://github.com/hasura/learn-graphql/commit/b4d3364492c4c6f356e94c2ddc55d6c37b0355b4
