### ISSUE TITLE
last_seen rule in auth0 tutorial doesn't work

### ISSUE THREAD

**Issue by imyjimmy** [hasura/learn-graphql#444]
This line:
`on_conflict: {constraint: users_pkey, update_columns: [last_seen, name]}`

is not working for me. last_seen remains null after log in.

**Comment by praveenweb** [comment]
@imyjimmy - This shouldn't happen if you are using the admin secret. Just confirming again that you were following the Hasura Basics tutorial?

**Comment by praveenweb** [comment]
@imyjimmy - I realised that there has been a change in the default value of `last_seen` column in the data modelling. I have now fixed it by adding the last_seen value inside the Auth0 rule. This should work now.

Thanks for reporting!
