### ISSUE TITLE
Flutter zip file - online_list.dart

### ISSUE THREAD

**Issue by alexjeanderae** [hasura/learn-graphql#446]
Thank you for the code in the zip file available through https://hasura.io/learn/graphql/flutter-graphql/boilerplate.zip

In the final app there is a file called online_list.dart

I dont see any other file in the app that imports it or calls the class OnlineList contained in it.

Am I missing something or is this legacy dead code?

**Comment by praveenweb** [comment]
Hi @alexjeanderae - This seems to have been fixed in one of the earlier updates for the both the zip file and the repo contents. Sorry about the delayed response.
