### ISSUE TITLE
Add labels for social icons, subscription forms, and emojis

### ISSUE THREAD

**Issue by itaditya** [hasura/learn-graphql#47]
Currently there are these accessibility bugs for visually impaired people 
<img width="580" alt="image" src="https://user-images.githubusercontent.com/15871340/66308631-342df680-e925-11e9-9ea7-6eb4385d7fed.png">

We should fix these, I can work on it

**Comment by itaditya** [comment]
also it would be nice if you add `hacktoberfest` label on this

**Comment by praveenweb** [comment]
@itaditya - Feel free to take up this issue :)

**Comment by chimon2000** [comment]
I would be glad to take this issue if it is not yet assigned @praveenweb

**Comment by itaditya** [comment]
@chimon2000 I have started working on this.

**Comment by itaditya** [comment]
@praveenweb please review the PR https://github.com/hasura/learn-graphql/pull/67

**Comment by itaditya** [comment]
I couldn't fix the text label issues for the subscription forms since the react-mailchimp-subscribe (v1.1.0) doesn't support prop to pass aria-labels. I think the newer version of it which is render prop based can be used for that. @chimon2000 you can pick up that task.  @praveenweb what do you think?
