### ISSUE TITLE
Suggestion to add link to Installing the Hasura CLI to learn/graphql/nextjs 

### ISSUE THREAD

**Issue by Shoryu-N** [hasura/learn-graphql#482]
Hi guys,
I’m new to Hasura and I think https://learn.hasura.io is a very helpful resource.

Now I’m doing https://hasura.io/learn/graphql/nextjs-fullstack-serverless/hasura-backend/ and
I thought it would be better if there was a link to https://hasura.io/docs/latest/graphql/core/hasura-cli/install-hasura-cli.html in the last chapter because this was the first time I saw `hasura` command in this tutorial.
 
Thanks for your attention

**Comment by praveenweb** [comment]
Hi @Shoryu-N :)

Thanks for the suggestion. This has now been added here - https://github.com/hasura/learn-graphql/blob/master/tutorials/frontend/nextjs/tutorial-site/content/hasura-backend.md#apply-database-migrations

via this PR https://github.com/hasura/learn-graphql/pull/498
