### ISSUE TITLE
learn: Hasura backend tutorial [remote-schemas]

### ISSUE THREAD

**Issue by waptik** [hasura/learn-graphql#5]
In [remote-schemas](https://learn.hasura.io/graphql/hasura/custom-business-logic/1-remote-schemas), the demo app is not working as it should. On [glitch](https://auth0-hasura-remote-schema.glitch.me/), this query

```js
# Write your query or mutation here
query {
  auth0 {
    email,
    picture
  }
}
```
displays some errors.

**Comment by alizhdanov** [comment]
Hey @praveenweb, I see `hacktoberfest` tag. But what exactly should be done? Just add more human-readable error, that  `Authorization` token is missing? It should be helpful for beginners.

**Comment by nik72619c** [comment]
Yes, I'd love to take this one up. Kindly guide me with this if this is still open to take it !

**Comment by praveenweb** [comment]
Unable to reproduce this. Closing this now.
