### ISSUE TITLE
auth-server throws error when using Node 14+

### ISSUE THREAD

**Issue by francispoole** [hasura/learn-graphql#521]
When using a Node version greater than 14, you receive the following error when attempting to interact with the auth-server to register users
```
{
  "message": "Knex: Timeout acquiring a connection. The pool is probably full. Are you missing a .transacting(trx) call?",
  "type": "UnknownError",
  "data": {}
}
```

This requires the `pg` dependency to be updated to v8.0.3 (see: https://github.com/knex/knex/issues/3831)

I'll raise a quick PR to fix this.

**Comment by catalinpit** [comment]
Thank you for your contribution!
