### ISSUE TITLE
No Rules page in Auth0 Dashboard

### ISSUE THREAD

**Issue by ironmanCCT** [hasura/learn-graphql#540]
This page: https://github.com/hasura/learn-graphql/blob/master/tutorials/backend/hasura/tutorial-site/content/authentication/2-custom-jwt-claims-rule.md?plain=1
directs the user to add a Rule but it's unclear what page of the dashboard that is.

**Comment by ironmanCCT** [comment]
It's currently under Auth Pipeline.

**Comment by praveenweb** [comment]
Hi @ironmanCCT - You are right. Auth0 updated their UI and hence some of the screenshots and instructions become obsolete. @catalinpit has updated these in this PR - https://github.com/hasura/learn-graphql/pull/552

Will deploy these changes shortly. Closing this now :)
