### ISSUE TITLE
Duplicate Japanese translation pages at custom-business-logic

### ISSUE THREAD

**Issue by Makohan** [hasura/learn-graphql#601]
I have found Duplicate Japanese translation pages at custom-business-logic.
It's created by [lilt-connector](https://github.com/hasura/learn-graphql/pull/546), but others is by manual.
Which pages is correct?

https://github.com/hasura/learn-graphql/tree/master/tutorials/backend/hasura/tutorial-site-ja/content/custom-business-logic

- incorrect pages
  - https://hasura.io/learn/ja/graphql/hasura/custom-business-logic/

**Comment by Makohan** [comment]
I have adjusted to other translation files.

https://github.com/hasura/learn-graphql/pull/602

**Comment by praveenweb** [comment]
@Makohan - Thanks for reporting this and fixing it via a PR. I have merged the changes now.
