### ISSUE TITLE
Rendering issue with tutorial dashboard

### ISSUE THREAD

**Issue by anujc4** [hasura/learn-graphql#62]
There is a bug in the dashboard causing the heading to display as normal text rather than a heading.

![image](https://user-images.githubusercontent.com/9458914/66461056-cfde7480-ea95-11e9-8de0-22bdbc11c5c7.png)

**Comment by anujc4** [comment]
Fix for the same has been added in [this](https://github.com/hasura/learn-graphql/pull/61) PR

**Comment by praveenweb** [comment]
Closed via 4ccfed6
