### ISSUE TITLE
Suggestion : update docs image in todo-app course for update permission

### ISSUE THREAD

**Issue by meetzaveri** [hasura/learn-graphql#642]
### Overview:
A suggestion to improve an image (to replace old with fresh new image) in documentation.

### Description:
I was going through a course in [hasura.io/learn](http://hasura.io/learn). I came across this link - https://hasura.io/learn/graphql/hasura/authorization/2-users-table-permissions/. There in update section, the image is of older console version I guess. In the latest console version, we do have two pre-update and post-update. So, just wanted to shred a light on this. As a long time user of hasura I was able to catch up with what docs were saying, but I think it will cause certain confusion for newbies.

### Screenshots for images (old and new)

**Older image (older console)** 
![old-users-update-permission](https://user-images.githubusercontent.com/21293048/166664747-02144ba6-5350-4fee-8af7-9e327e2f52de.png)

**New image (with latest console)**
![new-users-pre-update-post-update-permissions](https://user-images.githubusercontent.com/21293048/166664774-3bff2d4d-fe0e-45ef-a68a-6de6f52639a6.png)

**Comment by meetzaveri** [comment]
I would love to work on PR. But for that I'll need to deploy newer(latest console version) image to hasura's CDN sever and as I do not have permissions/authorization for that, I would need some help from someone who can deploy and share a link in this conversation.

**Comment by praveenweb** [comment]
Closed via https://github.com/hasura/learn-graphql/commit/fdfc83aa96463716ee7ac8210958c08cf1e1b0a0
