### ISSUE TITLE
git command in React tutorial setup doesn't work

### ISSUE THREAD

**Issue by mjohnsonengr** [hasura/learn-graphql#655]
On https://hasura.io/learn/graphql/react/setup/

The instructions say to run `git clone --filter=blob:none --sparse git@github.com:hasura/learn-graphql.git`

When I do this, I get the following error message:

```
Cloning into 'learn-graphql'...
fatal: cannot change to 'git@github.com:hasura/learn-graphql.git': No such file or directory
error: failed to initialize sparse-checkout
```

**Comment by mjohnsonengr** [comment]
I'm on WSL which ships with git 2.25 currently. Upgrading to 2.36 worked (presumably 2.26 would work too)

**Comment by FrankvandenBoogaard** [comment]
I'm on Ubuntu 20.04.4 LTS and got same error.
Used PPA available from Ubuntu Git Maintainers team (https://launchpad.net/~git-core/+archive/ubuntu/ppa) to install latest stable Git version:
-----
sudo add-apt-repository ppa:git-core/ppa
sudo apt update
sudo apt install git 
-----
Upgraded to 2.36.1 and now the command works.
