### ISSUE TITLE
Typo in documentation

### ISSUE THREAD

**Issue by otariki** [hasura/learn-graphql#679]
Hi 
Not sure if this is correct place to report that issue but don't know better one.
in doc (here: https://hasura.io/learn/graphql/intro-graphql/graphql-queries/) there is:

"The schema is a graph-like schema where all the 3 models are linked to each other. Since all 3 modes are linked, we can use nested queries."

I think this is typo and instead of "modes" it should be "models"

**Comment by kaleem68** [comment]
LGTM - should get merged.

**Comment by praveenweb** [comment]
Closed via https://github.com/hasura/learn-graphql/pull/682
