### ISSUE TITLE
Migrate class components to functional components

### ISSUE THREAD

**Issue by itaditya** [hasura/learn-graphql#68]
All components except `Testimonials.js` just have a render method. They don't use any special stuff which class components provide. Since there is a transpilation cost associated with class components, we should use function components instead.

Note- I'm not talking about adding hooks in the project. The only place where a hook would be useful is `Testimonials.js` but it is fine its current state. I'm just talking about other components which don't need hooks

**Comment by praveenweb** [comment]
@itaditya - Makes sense. Would you like to work on this?

**Comment by itaditya** [comment]
@praveenweb since I have already got three PRs merged, I'm eligible for Hasura Hacktoberfest t-shirt. So let's give this opportunity to someone else. If no one picks it up in the next two days, I'll work on it.

**Comment by deadcoder0904** [comment]
I'll tackle this one :)

**Comment by deadcoder0904** [comment]
Sent a PR https://github.com/hasura/learn-graphql/pull/70
