### ISSUE TITLE
Tutorial text about GraphQL endpoint being open is incorrect

### ISSUE THREAD

**Issue by heysc0tt** [hasura/learn-graphql#684]
https://github.com/hasura/learn-graphql/blob/0260fab2e73f3a04dfe14b5507c2566647b6e267/tutorials/backend/hasura/tutorial-site/content/authentication/3-setup-env-vars-hasura.md?plain=1#L9

Text states that:
>Before we do that, we need to secure our endpoint with an admin secret. Right now, the GraphQL endpoint is open and anybody can query and manage the data.

This seems misleading/incorrect as the new endpoint is created with a generated admin secret already as stated here:
https://hasura.io/docs/latest/graphql/cloud/projects/secure/#adding-an-admin-secret
>To make sure that your GraphQL endpoint is not publicly accessible, a randomly generated admin secret key is added by default to your project at the time of project creation.

**Comment by praveenweb** [comment]
@heysc0tt - Thanks for pointing this out. I have fixed it in this [commit](https://github.com/hasura/learn-graphql/commit/5bf2260f8b14449cbe54e58978f205f8e7c3f888). Hasura Cloud auto-generates admin secret for every project and hence the above note is not valid anymore, as you mentioned.
