### ISSUE TITLE
svelte-apollo error 'PORT' is not recognized...

### ISSUE THREAD

**Issue by beebase** [hasura/learn-graphql#708]
After npm install , npm run dev  I'm gettig this error.
```
> svelte-app@1.0.0 dev
> PORT=3000 rollup -c -w

'PORT' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by praveenweb** [comment]
@beebase - Thanks for reporting the issue. I have added a note on the [setup page instructions](https://github.com/hasura/learn-graphql/commit/7cc67d109d5a1f68daa18dde646a6810afb6f4d6).
