### ISSUE TITLE
create learn tutorial for svelte + apollo

### ISSUE THREAD

**Issue by praveenweb** [hasura/learn-graphql#71]
[Svelte](https://svelte.dev) is a framework for building reactive user interfaces. Using the same learn.hasura.io GraphQL Backend, we need to build the realtime todo app with svelte-apollo along with the tutorial content.

**Comment by nik72619c** [comment]
shall I give it a try if its still open ot work on ?

**Comment by nik72619c** [comment]
@praveenweb shall I work on this ?

**Comment by praveenweb** [comment]
@nik72619c - Hi, it is still open and you are welcome to create a PR :)

There has been interests from other users (@vardhanapoorv) as well to build this. Let's structure this so that there is no repeat work.

**Comment by nik72619c** [comment]
Okay, could you provide me any direction for working ?

**Comment by praveenweb** [comment]
Folks, thanks for the interest. 

This has now been merged via https://github.com/hasura/learn-graphql/pull/487
