### ISSUE TITLE
Add contributor label in readme file

### ISSUE THREAD

**Issue by Hariom8799** [hasura/learn-graphql#785]
![Capture](https://user-images.githubusercontent.com/76242202/194721139-e9f3f5c6-da12-4465-b566-ba32d5707318.PNG)
like this

**Comment by Sidd2024** [comment]
hey,@Hariom8799 I would like to work on this issue.👋🏻

**Comment by Hariom8799** [comment]
@Sidd2024 bro sorry, pls find another one

**Comment by Hariom8799** [comment]
Pls assign me for this

**Comment by Sidd2024** [comment]
Oh sorry my bad😅...

**Comment by praveenweb** [comment]
@Hariom8799 - Feel free to open a PR for this
