### ISSUE TITLE
request: add PR template

### ISSUE THREAD

**Issue by akebu6** [hasura/learn-graphql#786]
add a PR template that contributors will use to check their work against the accepted standards of the project their are contributing to

**Comment by shikhar13012001** [comment]
Hi @akebu6 I would like to work on this issue , Can you please assign this to me?

**Comment by AbhishekTiwari23** [comment]
I am also ready with my set up please assign

**Comment by koconder** [comment]
Created https://github.com/hasura/learn-graphql/pull/795 based on the main repo's PR template
